baseurl = "/"
languageCode = "es"
title = "Tyler S Smith"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Tyler S Smith"
	description = "Sitio Personal de Tyler S Smith."

	# Format dates with Go's time formatting
	date_format = "01-02-2006"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "IMG_1630.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Soi Tyler**, un programador creando mi propio sitio."
		# The icons will be shown if you enter your username
		twitter = "TylerPuddle"
		github = "TylerSSmith"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Tyler Smith",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
  		title = "Sobre mi"
		content = "Soi un estudiante de las ciencias de la computación en Southern Virginia University. Tambien soy esposo, padre, y entusiasta de la tecnología."


	[params.portfolio]
		hide  = false
		title = "Projectos Recientes"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Mi Proyecto Más Reciente."
			description = "Descriptio'n de este proyecto."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Second recent Work."
			description = "Description of second work."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Mándame un mensaje o me puede contactar por correo electronico o por telephono."

		address = [
			"Buena Vista, VA",
			"United States"
		]
		phone = "503-367-8101"
		email = "tyler.smith@students.svu.edu"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nombre"
			email = "Correo Electronico"
			message = "Mensaje"
			submit = "Envi'a Mensaje"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Inicio"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Sobre"
	url  = "about"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
